
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      storage: localStorage
    }
  }
);

// Add auth listener and session management
export const initSupabaseAuth = () => {
  const { data: { subscription } } = supabase.auth.onAuthStateChange(
    (event, session) => {
      // Update session state when auth state changes
      console.log("Auth state changed", event, session);
    }
  );

  return subscription;
};

// Auth helper functions - these will be replaced by Clerk
export const getSession = async () => {
  const { data, error } = await supabase.auth.getSession();
  return { data, error };
};
