
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Create Supabase client with anon key and explicit auth storage config
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_ANON_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    }
  }
);

// Function to get Supabase client with custom auth token
export const getSupabaseWithAuth = (jwt: string) => {
  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    global: {
      headers: {
        Authorization: `Bearer ${jwt}`
      }
    },
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    }
  });
};

// Add auth listener and session management
export const initSupabaseAuth = () => {
  const { data: { subscription } } = supabase.auth.onAuthStateChange(
    (event, session) => {
      // Update session state when auth state changes
      console.log("Auth state changed", event, session);
    }
  );

  return subscription;
};

// Auth helper functions 
export const getSession = async () => {
  const { data, error } = await supabase.auth.getSession();
  return { data, error };
};

// Add a function to sign in anonymously to enable using RLS
export const signInAnonymously = async () => {
  // Check for existing session first
  const { data: sessionData } = await supabase.auth.getSession();
  
  if (sessionData.session) {
    console.log('Session already exists, no need to sign in anonymously');
    return { data: sessionData, error: null };
  }
  
  // No session, try to sign in anonymously
  const { data, error } = await supabase.auth.signInAnonymously();
  
  if (error) {
    console.error('Error signing in anonymously:', error);
  } else {
    console.log('Signed in anonymously successfully');
  }
  
  return { data, error };
};
